### ISSUE TITLE
"deconstify" was not declared in this scope

### ISSUE THREAD

**Issue by janEntikan** [rdb/nim-panda3d#7]
Whenever I call a function that uses "deconstify" I get the following error:

```
/home/olbora/.cache/nim/main_d/@mmain.nim.cpp: In function 'void NimMainModule()':
/home/olbora/.cache/nim/main_d/@mmain.nim.cpp:338:30: error: 'deconstify' was not declared in this scope
  338 |         transform__main_10 = deconstify(TransformState::make_scale2d(1.0));
```
I've tried with both `GeomVertexData.getV3n3c4t2()` and `TransformState.makeScale2d(1.0)` (error above).

**Comment by rdb** [comment]
It's because the header needed to include TransformState supersedes the code that pulls in deconstify, because the header pragma only supports a single header (or blob of code).

I think deconstify should just be added to the Panda source proper so we don't have to have custom helpers, but in the meantime, I will put the deconstify helper in a header file.
